---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ducklake-featherman-dev-v1alpha1-ducklakecatalog
  failurePolicy: Fail
  name: mducklakecatalog.kb.io
  rules:
  - apiGroups:
    - ducklake.featherman.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ducklakecatalogs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ducklake-featherman-dev-v1alpha1-ducklaketable
  failurePolicy: Fail
  name: mducklaketable.kb.io
  rules:
  - apiGroups:
    - ducklake.featherman.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ducklaketables
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ducklake-featherman-dev-v1alpha1-ducklakecatalog
  failurePolicy: Fail
  name: vducklakecatalog.kb.io
  rules:
  - apiGroups:
    - ducklake.featherman.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ducklakecatalogs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ducklake-featherman-dev-v1alpha1-ducklaketable
  failurePolicy: Fail
  name: vducklaketable.kb.io
  rules:
  - apiGroups:
    - ducklake.featherman.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ducklaketables
  sideEffects: None
