apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: featherman-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: featherman-manager-role
subjects:
  - kind: ServiceAccount
    name: featherman-controller-manager
    namespace: featherman-system
