---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ducklake.featherman.dev
  resources:
  - ducklakecatalogs
  - ducklaketables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ducklake.featherman.dev
  resources:
  - ducklakecatalogs/finalizers
  - ducklaketables/finalizers
  verbs:
  - update
- apiGroups:
  - ducklake.featherman.dev
  resources:
  - ducklakecatalogs/status
  - ducklaketables/status
  verbs:
  - get
  - patch
  - update
